version: '2'
services:
  database:
    image: mongo:latest
    command: mongod --smallfiles
    ports:
      - "27017:27017"
  moboko:
    image: alexsandrospecht/moboko:latest
    ports:
     - "80:80"
     - "3000:3000"
    environment:
     - MONGO_URL=mongodb://database:27017/moboko
     - ROOT_URL=http://teste.com
    depends_on:
     - database
    links:
     - database
